export const DEFAULT_SKILLS = [
  "JavaScript", "TypeScript", "Python", "Java", "C", "C++", "C#", "Go", "Rust", "Kotlin",
  "Swift", "Ruby", "PHP", "Scala", "R", "MATLAB", "Dart", "Elixir", "Erlang", "Haskell",
  "Lua", "Perl", "Objective-C", "Shell Scripting", "Bash", "PowerShell", "SQL", "NoSQL",
  "HTML", "CSS", "Sass", "Less", "Tailwind CSS", "Bootstrap", "Material UI", "Chakra UI",
  "Ant Design", "Styled Components", "Emotion", "Responsive Design", "Web Accessibility",
  "WCAG", "React", "Next.js", "Vue.js", "Nuxt", "Angular", "Svelte", "SvelteKit", "Redux",
  "Redux Toolkit", "Zustand", "MobX", "React Query", "TanStack Query", "Apollo Client",
  "GraphQL", "REST APIs", "WebSockets", "Socket.IO", "tRPC", "gRPC", "Micro Frontends",
  "Webpack", "Vite", "Rollup", "Parcel", "Babel", "ESLint", "Prettier", "Storybook",
  "Jest", "Vitest", "React Testing Library", "Cypress", "Playwright", "Selenium",
  "Node.js", "Express.js", "Fastify", "NestJS", "Django", "Flask", "FastAPI", "Spring Boot",
  "ASP.NET Core", "Laravel", "Ruby on Rails", "Phoenix", "Gin", "Fiber", "Koa", "Hono",
  "Prisma", "TypeORM", "Sequelize", "Mongoose", "Hibernate", "Entity Framework",
  "PostgreSQL", "MySQL", "SQLite", "Microsoft SQL Server", "Oracle Database", "MongoDB",
  "Redis", "Elasticsearch", "OpenSearch", "DynamoDB", "Cassandra", "Couchbase", "Neo4j",
  "Firebase", "Supabase", "PlanetScale", "CockroachDB", "ClickHouse", "Snowflake",
  "BigQuery", "Redshift", "Databricks", "Apache Spark", "Apache Flink", "Kafka",
  "RabbitMQ", "NATS", "SQS", "Pub/Sub", "Celery", "BullMQ", "Temporal", "Airflow",
  "Docker", "Kubernetes", "Helm", "Terraform", "Pulumi", "Ansible", "GitHub Actions",
  "GitLab CI", "Jenkins", "CircleCI", "Azure DevOps", "Argo CD", "Flux CD", "CI/CD",
  "Linux", "Ubuntu", "Nginx", "Apache HTTP Server", "Caddy", "Load Balancing", "CDN",
  "Cloudflare", "AWS", "Amazon EC2", "Amazon S3", "AWS Lambda", "Amazon RDS", "Amazon ECS",
  "Amazon EKS", "Amazon CloudWatch", "AWS IAM", "Google Cloud", "Cloud Run", "Cloud Functions",
  "Google Kubernetes Engine", "Google Cloud Storage", "Firebase Hosting", "Azure",
  "Azure Functions", "Azure App Service", "Azure Kubernetes Service", "Vercel", "Netlify",
  "Render", "Railway", "Fly.io", "Heroku", "DigitalOcean", "System Design",
  "Distributed Systems", "Microservices", "Monolith Architecture", "Event Driven Architecture",
  "Domain Driven Design", "Clean Architecture", "Hexagonal Architecture", "API Design",
  "Database Design", "Data Modeling", "Caching", "Sharding", "Replication", "Message Queues",
  "Rate Limiting", "Observability", "Monitoring", "Logging", "Tracing", "OpenTelemetry",
  "Prometheus", "Grafana", "Datadog", "Sentry", "New Relic", "Security Engineering",
  "OAuth", "OAuth 2.0", "OpenID Connect", "JWT", "Session Management", "RBAC", "ABAC",
  "SSO", "SAML", "Encryption", "TLS", "OWASP", "Penetration Testing", "Secure Coding",
  "Application Security", "Network Security", "Cloud Security", "DevSecOps", "Zero Trust",
  "Machine Learning", "Deep Learning", "Natural Language Processing", "Computer Vision",
  "Generative AI", "Prompt Engineering", "LLM Evaluation", "RAG", "Vector Databases",
  "Embeddings", "LangChain", "LlamaIndex", "OpenAI API", "Hugging Face", "PyTorch",
  "TensorFlow", "Keras", "scikit-learn", "Pandas", "NumPy", "SciPy", "Matplotlib",
  "Seaborn", "Plotly", "Jupyter", "Feature Engineering", "Model Deployment", "MLOps",
  "Data Analysis", "Data Visualization", "Data Warehousing", "ETL", "ELT", "dbt",
  "Data Pipelines", "Business Intelligence", "Power BI", "Tableau", "Looker", "Excel",
  "Google Sheets", "A/B Testing", "Experiment Design", "Statistics", "Product Analytics",
  "Mixpanel", "Amplitude", "Google Analytics", "Mobile Development", "React Native",
  "Flutter", "Android Development", "iOS Development", "SwiftUI", "Jetpack Compose",
  "Expo", "Mobile UI Design", "App Store Optimization", "Push Notifications",
  "Game Development", "Unity", "Unreal Engine", "Godot", "Three.js", "WebGL", "WebGPU",
  "ARKit", "ARCore", "Blockchain", "Ethereum", "Solidity", "Smart Contracts", "Web3.js",
  "Ethers.js", "Hardhat", "Foundry", "IPFS", "DeFi", "NFTs", "Product Management",
  "Roadmapping", "User Research", "Market Research", "Competitive Analysis", "PRD Writing",
  "Product Strategy", "Go-to-Market Strategy", "Growth Strategy", "Growth Marketing",
  "SEO", "Technical SEO", "Content Strategy", "Copywriting", "Email Marketing",
  "Lifecycle Marketing", "Performance Marketing", "Paid Search", "Paid Social",
  "CRM", "HubSpot", "Salesforce", "Customer Success", "Account Management", "B2B Sales",
  "Lead Generation", "Sales Operations", "Revenue Operations", "Operations Management",
  "Project Management", "Program Management", "Agile", "Scrum", "Kanban", "Jira",
  "Confluence", "Notion", "Asana", "Trello", "Linear", "Figma", "FigJam", "Sketch",
  "Adobe XD", "Adobe Photoshop", "Adobe Illustrator", "Adobe After Effects", "Canva",
  "UI Design", "UX Design", "Interaction Design", "Design Systems", "Wireframing",
  "Prototyping", "User Testing", "Information Architecture", "Visual Design",
  "Brand Design", "Motion Design", "Technical Writing", "Documentation", "Public Speaking",
  "Presentation Skills", "Stakeholder Management", "Leadership", "Mentoring", "Teamwork",
  "Communication", "Problem Solving", "Critical Thinking", "Time Management", "Negotiation",
  "Hiring", "Interviewing", "Code Review", "Debugging", "Performance Optimization",
  "Refactoring", "Algorithms", "Data Structures", "Object Oriented Programming",
  "Functional Programming", "Test Driven Development", "Behavior Driven Development",
  "Unit Testing", "Integration Testing", "End to End Testing", "API Testing", "Load Testing",
  "Performance Testing", "Accessibility Testing", "QA Automation", "Manual Testing",
  "Release Management", "Incident Management", "SRE", "IT Support", "Networking",
  "DNS", "TCP/IP", "VPN", "Active Directory", "Windows Server", "macOS", "Git", "GitHub",
  "GitLab", "Bitbucket", "SVN", "Package Management", "npm", "pnpm", "Yarn", "Maven",
  "Gradle", "Composer", "Pip", "Poetry", "Conda", "Figma to Code", "CMS", "WordPress",
  "Shopify", "Webflow", "Strapi", "Sanity", "Contentful", "Headless CMS", "Stripe",
  "Razorpay", "PayPal", "Payment Gateways", "FinTech", "HealthTech", "EdTech",
  "E-commerce", "Marketplace Platforms", "SaaS", "B2B", "B2C", "Customer Discovery",
  "Data Privacy", "GDPR", "SOC 2", "ISO 27001", "Compliance", "Risk Management",
  "Financial Modeling", "Accounting", "Budgeting", "Forecasting", "Supply Chain",
  "Logistics", "Procurement", "Human Resources", "Talent Acquisition", "Employee Engagement"
] as const;

export type DefaultSkill = (typeof DEFAULT_SKILLS)[number];

export function normalizeSkillName(name: string): string {
  return name.trim().replace(/\s+/g, " ").toLowerCase();
}
