import generatedCatalog from "@/generated/public-question-catalog.json";

export type PublicQuestionCategory = "coding" | "cs-fundamentals" | "system-design" | "sql";

export type PublicQuestionPreview = {
  frontendId: string;
  slug: string;
  title: string;
  category: PublicQuestionCategory;
  difficulty: "Easy" | "Medium" | "Hard";
  tags: string[];
  acceptanceRate: number;
  summary: string;
  prompt: string;
  tests: string[];
  schema?: unknown;
  examples?: Array<{
    input?: unknown;
    output?: unknown;
    explanation?: string;
  }>;
  hints?: string[];
  followUpQuestions?: string[];
  commonMistake: string;
  approachHint: string;
  starterCode: string;
  language: "cpp" | "text" | "sql";
  authPath: string;
};

export function normalizeQuestionTypography(value: string) {
  return String(value || "")
    .replace(/[\u2013\u2014]/g, "-");
}

export const questionCategories: Record<PublicQuestionCategory, {
  label: string;
  shortLabel: string;
  href: string;
  heroTitle: string;
  heroHighlight: string;
  heroDescription: string;
  description: string;
  seoBlockTitle: string;
  seoBlock: string;
  emptySearchHint: string;
  seoIntro: string;
}> = {
  coding: {
    label: "Coding Interview Questions",
    shortLabel: "Coding",
    href: "/interview-questions/coding",
    heroTitle: "View Mockr coding interview question bank",
    heroHighlight: "coding",
    heroDescription: "Practice DSA, algorithms, data structures, complexity analysis, examples, hints, and approach notes before solving in the Mockr IDE.",
    description: "Preview coding interview questions for DSA, algorithms, data structures, and complexity analysis before solving them in the Mockr IDE.",
    seoBlockTitle: "Coding interview practice with DSA, algorithms, and data structures",
    seoBlock: "This coding interview question bank is built for software engineering preparation across arrays, strings, trees, graphs, dynamic programming, sorting, searching, and time complexity. You can scan the prompt publicly, understand the expected approach, and choose when to move into the Mockr IDE for hands-on coding practice. It is useful for quick DSA revision, structured algorithm practice, and long-tail preparation for common technical interview questions.",
    emptySearchHint: "Try a broader keyword like array, graph, tree, dynamic programming, sorting, or complexity.",
    seoIntro: "Coding interview questions help you build the problem-solving muscle expected in software engineering rounds.",
  },
  "cs-fundamentals": {
    label: "CS Fundamentals Questions",
    shortLabel: "CS Fundamentals",
    href: "/interview-questions/cs-fundamentals",
    heroTitle: "View Mockr CS fundamentals question bank",
    heroHighlight: "CS fundamentals",
    heroDescription: "Revise operating systems, DBMS, computer networking, OOP, concurrency, memory management, and core CS interview questions.",
    description: "Revise CS fundamentals questions across operating systems, DBMS, computer networks, OOP, concurrency, and core software concepts.",
    seoBlockTitle: "CS fundamentals questions for core computer science revision",
    seoBlock: "Use this CS fundamentals question bank to prepare for theory-heavy interview rounds covering operating systems, DBMS, computer networks, object-oriented programming, concurrency, memory management, transactions, indexing, and protocols. Each preview helps you understand what the interviewer is testing before you answer in detail. It is designed for candidates who want quick revision as well as deeper practice before technical screens.",
    emptySearchHint: "Try a broader keyword like OS, DBMS, network, OOP, thread, process, transaction, or indexing.",
    seoIntro: "CS fundamentals interview questions test whether you understand the concepts behind the code you write.",
  },
  "system-design": {
    label: "System Design Interview Questions",
    shortLabel: "System Design",
    href: "/interview-questions/system-design",
    heroTitle: "View Mockr system design question bank",
    heroHighlight: "system design",
    heroDescription: "Practice system design questions on scalable architecture, APIs, databases, caching, queues, reliability, capacity planning, and trade-offs.",
    description: "Work through system design interview prompts on APIs, databases, caching, queues, scalability, reliability, and architecture trade-offs.",
    seoBlockTitle: "System design interview prompts for architecture practice",
    seoBlock: "This system design question bank focuses on architecture thinking, requirement clarification, API design, database modeling, caching strategies, queues, reliability, scaling, monitoring, and trade-offs. Public previews let you pick the right design prompt before opening the workspace. It is suited for backend, full-stack, and senior engineering interview preparation where communication and design reasoning matter as much as the final architecture.",
    emptySearchHint: "Try a broader keyword like cache, queue, API, database, scaling, rate limiter, feed, or chat.",
    seoIntro: "System design interview questions are built to test architecture thinking, constraints, trade-offs, and communication.",
  },
  sql: {
    label: "SQL Interview Questions",
    shortLabel: "SQL",
    href: "/interview-questions/sql",
    heroTitle: "View Mockr SQL interview question bank",
    heroHighlight: "SQL",
    heroDescription: "Preview SQL interview questions on joins, GROUP BY, filtering, window functions, subqueries, aggregations, reporting queries, and databases.",
    description: "Explore SQL interview questions for joins, grouping, filtering, window functions, subqueries, reporting logic, and database problem solving.",
    seoBlockTitle: "SQL interview practice for queries, joins, and reporting logic",
    seoBlock: "This SQL interview question bank helps you practice database query problems around joins, GROUP BY, HAVING, filtering, subqueries, window functions, aggregations, ranking, retention, and reporting metrics. You can preview the business-style prompt first, then open the same problem in the Mockr workspace when you are ready to write and test a query. It is built for analyst, data, backend, and software interview preparation.",
    emptySearchHint: "Try a broader keyword like joins, aggregation, subquery, window function, ranking, retention, or GROUP BY.",
    seoIntro: "SQL interview questions check whether you can turn business conditions into accurate database queries.",
  },
};

const starter = {
  cpp: "class Solution {\npublic:\n    // Write your solution here\n};",
  text: "Structure your answer:\n\n1. Clarify requirements\n2. Explain the core idea\n3. Discuss trade-offs\n4. Mention edge cases",
  sql: "-- Write your SQL query here\nSELECT\n  -- columns\nFROM table_name;",
};

function authPath(category: PublicQuestionCategory, slug: string) {
  if (category === "coding") return `/questions/dsa/solve?id=${slug}`;
  if (category === "cs-fundamentals") return `/questions/cs-fundamentals/solve?id=${slug}`;
  if (category === "system-design") return `/questions/system-design/solve?id=${slug}`;
  return `/questions/sql/solve?id=${slug}`;
}

function q(input: Omit<PublicQuestionPreview, "authPath" | "starterCode" | "language"> & {
  language?: PublicQuestionPreview["language"];
  starterCode?: string;
}): PublicQuestionPreview {
  const language = input.language ?? (input.category === "sql" ? "sql" : input.category === "coding" ? "cpp" : "text");
  return {
    ...input,
    language,
    starterCode: input.starterCode ?? starter[language],
    authPath: authPath(input.category, input.slug),
  };
}

const fallbackQuestions: PublicQuestionPreview[] = [
  q({
    frontendId: "1",
    slug: "two-sum",
    title: "Two Sum",
    category: "coding",
    difficulty: "Easy",
    tags: ["Arrays", "Hash Map", "Time Complexity"],
    acceptanceRate: 87,
    summary: "A classic coding interview question that tests whether you can move from brute force to a hash map solution.",
    prompt: "Given an array of integers and a target value, return the indices of two numbers that add up to the target. Each input has exactly one valid answer, and you may not use the same element twice.",
    tests: ["nums = [2, 7, 11, 15], target = 9 -> [0, 1]", "nums = [3, 2, 4], target = 6 -> [1, 2]"],
    commonMistake: "Many candidates start with nested loops and never explain the O(n) improvement using a hash map.",
    approachHint: "Track values already seen and check whether the complement exists before storing the current number.",
  }),
  q({
    frontendId: "2",
    slug: "merge-intervals",
    title: "Merge Intervals",
    category: "coding",
    difficulty: "Medium",
    tags: ["Arrays", "Sorting", "Intervals"],
    acceptanceRate: 72,
    summary: "A common technical interview problem for checking sorting, boundary handling, and clean explanation.",
    prompt: "Given a collection of intervals, merge all overlapping intervals and return the non-overlapping intervals that cover all input ranges.",
    tests: ["[[1,3],[2,6],[8,10],[15,18]] -> [[1,6],[8,10],[15,18]]", "[[1,4],[4,5]] -> [[1,5]]"],
    commonMistake: "Forgetting that touching intervals such as [1,4] and [4,5] should be merged.",
    approachHint: "Sort intervals by start time, then maintain the last merged interval while scanning left to right.",
  }),
  q({
    frontendId: "3",
    slug: "longest-substring-without-repeating-characters",
    title: "Longest Substring Without Repeating Characters",
    category: "coding",
    difficulty: "Medium",
    tags: ["Strings", "Sliding Window", "Hash Set"],
    acceptanceRate: 69,
    summary: "A sliding window question that checks pointer movement and duplicate handling.",
    prompt: "Given a string, find the length of the longest substring without repeating characters.",
    tests: ["s = \"abcabcbb\" -> 3", "s = \"bbbbb\" -> 1"],
    commonMistake: "Moving the left pointer one step at a time without using the last seen index.",
    approachHint: "Keep the latest index for each character and move the left boundary only forward.",
  }),
  q({
    frontendId: "4",
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    category: "coding",
    difficulty: "Easy",
    tags: ["Stack", "Strings"],
    acceptanceRate: 82,
    summary: "A stack-based coding question for testing simple state management.",
    prompt: "Given a string containing brackets, determine whether every opening bracket is closed in the correct order.",
    tests: ["s = \"()[]{}\" -> true", "s = \"([)]\" -> false"],
    commonMistake: "Only counting brackets instead of validating order.",
    approachHint: "Push opening brackets and compare each closing bracket against the stack top.",
  }),
  q({
    frontendId: "5",
    slug: "binary-tree-level-order-traversal",
    title: "Binary Tree Level Order Traversal",
    category: "coding",
    difficulty: "Medium",
    tags: ["Trees", "BFS", "Queue"],
    acceptanceRate: 75,
    summary: "A tree traversal problem that tests breadth-first search and clean output grouping.",
    prompt: "Return the level order traversal of a binary tree's values as a list of levels.",
    tests: ["root = [3,9,20,null,null,15,7] -> [[3],[9,20],[15,7]]", "root = [] -> []"],
    commonMistake: "Not separating one level from the next while using the queue.",
    approachHint: "For each BFS round, capture the current queue size and process exactly that many nodes.",
  }),
  q({
    frontendId: "6",
    slug: "top-k-frequent-elements",
    title: "Top K Frequent Elements",
    category: "coding",
    difficulty: "Medium",
    tags: ["Heap", "Hash Map", "Bucket Sort"],
    acceptanceRate: 71,
    summary: "A frequency question where candidates compare heap and bucket-sort trade-offs.",
    prompt: "Given an integer array and k, return the k most frequent elements in any order.",
    tests: ["nums = [1,1,1,2,2,3], k = 2 -> [1,2]", "nums = [1], k = 1 -> [1]"],
    commonMistake: "Sorting the full array without discussing a better frequency-based approach.",
    approachHint: "Count frequencies first, then use a heap or frequency buckets to extract the top k.",
  }),
  q({
    frontendId: "7",
    slug: "number-of-islands",
    title: "Number of Islands",
    category: "coding",
    difficulty: "Medium",
    tags: ["Graphs", "DFS", "BFS", "Matrix"],
    acceptanceRate: 68,
    summary: "A grid traversal interview question that checks visited state and graph thinking.",
    prompt: "Given a 2D grid of land and water, count the number of islands formed by connected land cells.",
    tests: ["grid with one connected land mass -> 1", "grid with three separated land masses -> 3"],
    commonMistake: "Counting each land cell instead of marking all cells in the same connected component.",
    approachHint: "When you find unvisited land, run DFS or BFS to mark the full island.",
  }),
  q({
    frontendId: "8",
    slug: "coin-change",
    title: "Coin Change",
    category: "coding",
    difficulty: "Medium",
    tags: ["Dynamic Programming", "Arrays"],
    acceptanceRate: 61,
    summary: "A dynamic programming problem about minimum coins and unreachable states.",
    prompt: "Given coin denominations and an amount, return the fewest coins needed to make that amount, or -1 if impossible.",
    tests: ["coins = [1,2,5], amount = 11 -> 3", "coins = [2], amount = 3 -> -1"],
    commonMistake: "Using greedy logic for coin systems where greedy is not guaranteed.",
    approachHint: "Let dp[x] be the minimum coins needed for amount x and build from 0 to amount.",
  }),
  q({
    frontendId: "9",
    slug: "kth-largest-element-in-an-array",
    title: "Kth Largest Element in an Array",
    category: "coding",
    difficulty: "Medium",
    tags: ["Heap", "Quickselect", "Sorting"],
    acceptanceRate: 66,
    summary: "A selection problem where interviewers expect heap or quickselect reasoning.",
    prompt: "Find the kth largest element in an unsorted array without necessarily sorting the entire array.",
    tests: ["nums = [3,2,1,5,6,4], k = 2 -> 5", "nums = [3,2,3,1,2,4,5,5,6], k = 4 -> 4"],
    commonMistake: "Sorting immediately without discussing the O(n log k) heap option.",
    approachHint: "Maintain a min-heap of size k or use quickselect for expected linear time.",
  }),
  q({
    frontendId: "10",
    slug: "serialize-and-deserialize-binary-tree",
    title: "Serialize and Deserialize Binary Tree",
    category: "coding",
    difficulty: "Hard",
    tags: ["Trees", "DFS", "Design"],
    acceptanceRate: 48,
    summary: "A hard coding interview question that tests representation, recursion, and edge cases.",
    prompt: "Design an algorithm to serialize a binary tree into a string and deserialize the string back into the original tree.",
    tests: ["root = [1,2,3,null,null,4,5] -> same tree after decode", "root = [] -> []"],
    commonMistake: "Omitting null markers, which makes the tree impossible to reconstruct uniquely.",
    approachHint: "Use preorder traversal with explicit null tokens, then rebuild by consuming tokens in order.",
  }),

  q({
    frontendId: "1",
    slug: "deadlock-vs-starvation",
    title: "Deadlock vs Starvation",
    category: "cs-fundamentals",
    difficulty: "Medium",
    tags: ["Operating Systems", "Concurrency", "Processes"],
    acceptanceRate: 74,
    summary: "Compare two similar OS concepts with examples, causes, and prevention techniques.",
    prompt: "Explain the difference between deadlock and starvation. Give one example of each and describe how a system can prevent or reduce them.",
    tests: ["Mention circular wait or resource ordering for deadlock.", "Mention unfair scheduling, priority aging, or fairness for starvation."],
    commonMistake: "Saying both mean a process is stuck without explaining the difference in cause.",
    approachHint: "Define each term first, then contrast cause, duration, and prevention technique.",
  }),
  q({
    frontendId: "2",
    slug: "indexing-in-dbms",
    title: "Indexing in DBMS",
    category: "cs-fundamentals",
    difficulty: "Medium",
    tags: ["DBMS", "Indexes", "Query Optimization"],
    acceptanceRate: 78,
    summary: "Explain how indexes speed up reads and what trade-offs they introduce.",
    prompt: "What is indexing in DBMS? Explain how an index improves query performance and when adding too many indexes can hurt performance.",
    tests: ["Mention faster lookup or reduced scan cost.", "Mention write overhead, storage, and maintenance cost."],
    commonMistake: "Only saying indexes make queries faster without explaining read-write trade-offs.",
    approachHint: "Use a book index analogy, then move into B-tree or hash index behavior and trade-offs.",
  }),
  q({
    frontendId: "3",
    slug: "process-vs-thread",
    title: "Process vs Thread",
    category: "cs-fundamentals",
    difficulty: "Easy",
    tags: ["Operating Systems", "Threads", "Memory"],
    acceptanceRate: 83,
    summary: "A common OS interview question about isolation, shared memory, and scheduling.",
    prompt: "Explain the difference between a process and a thread. Include memory isolation, communication cost, and crash impact.",
    tests: ["Mention separate address space for processes.", "Mention shared memory inside a process for threads."],
    commonMistake: "Only saying threads are lightweight without explaining why.",
    approachHint: "Compare memory, communication, creation overhead, and failure isolation.",
  }),
  q({
    frontendId: "4",
    slug: "tcp-vs-udp",
    title: "TCP vs UDP",
    category: "cs-fundamentals",
    difficulty: "Easy",
    tags: ["Computer Networks", "Transport Layer"],
    acceptanceRate: 85,
    summary: "A networking question about reliability, ordering, latency, and real-world usage.",
    prompt: "Compare TCP and UDP. When would you choose each protocol in a real system?",
    tests: ["Mention TCP reliability and ordering.", "Mention UDP lower overhead and use cases like streaming or gaming."],
    commonMistake: "Calling UDP unreliable without explaining why it can still be useful.",
    approachHint: "Use concrete examples: file transfer for TCP, live streaming or DNS-style lookups for UDP.",
  }),
  q({
    frontendId: "5",
    slug: "normalization-in-dbms",
    title: "Normalization in DBMS",
    category: "cs-fundamentals",
    difficulty: "Medium",
    tags: ["DBMS", "Normalization", "Schema Design"],
    acceptanceRate: 76,
    summary: "A database design question about redundancy, anomalies, and table decomposition.",
    prompt: "What is normalization in DBMS? Explain why it is used and what trade-offs it can create.",
    tests: ["Mention reducing redundancy and update anomalies.", "Mention possible join cost or denormalization trade-offs."],
    commonMistake: "Listing normal forms without explaining the practical reason behind them.",
    approachHint: "Start with redundancy and anomalies, then explain 1NF, 2NF, 3NF at a high level.",
  }),
  q({
    frontendId: "6",
    slug: "acid-properties",
    title: "ACID Properties",
    category: "cs-fundamentals",
    difficulty: "Medium",
    tags: ["DBMS", "Transactions", "Consistency"],
    acceptanceRate: 80,
    summary: "A transaction question about atomicity, consistency, isolation, and durability.",
    prompt: "Explain ACID properties using an example such as a bank transfer.",
    tests: ["Define all four properties.", "Use a concrete transaction example."],
    commonMistake: "Explaining consistency vaguely without tying it to valid database state.",
    approachHint: "Use one example and show how each ACID property protects correctness.",
  }),
  q({
    frontendId: "7",
    slug: "paging-vs-segmentation",
    title: "Paging vs Segmentation",
    category: "cs-fundamentals",
    difficulty: "Medium",
    tags: ["Operating Systems", "Memory Management"],
    acceptanceRate: 69,
    summary: "An OS memory-management question about fixed-size pages and logical segments.",
    prompt: "Compare paging and segmentation. Explain how each divides memory and what problems each solves.",
    tests: ["Mention fixed-size pages.", "Mention logical variable-size segments."],
    commonMistake: "Mixing up page frames and logical program segments.",
    approachHint: "Contrast unit size, programmer visibility, fragmentation, and address translation.",
  }),
  q({
    frontendId: "8",
    slug: "http-vs-https",
    title: "HTTP vs HTTPS",
    category: "cs-fundamentals",
    difficulty: "Easy",
    tags: ["Computer Networks", "Security", "TLS"],
    acceptanceRate: 88,
    summary: "A web fundamentals question about encryption, certificates, and secure transport.",
    prompt: "What is the difference between HTTP and HTTPS? Explain what TLS adds to the request flow.",
    tests: ["Mention encryption and certificate-based identity.", "Mention protection against tampering and snooping."],
    commonMistake: "Saying HTTPS is only HTTP on port 443 without explaining TLS.",
    approachHint: "Explain confidentiality, integrity, authentication, and the certificate handshake at a high level.",
  }),
  q({
    frontendId: "9",
    slug: "oop-pillars",
    title: "Four Pillars of OOP",
    category: "cs-fundamentals",
    difficulty: "Easy",
    tags: ["OOP", "Design", "Programming"],
    acceptanceRate: 86,
    summary: "A foundational OOP question about encapsulation, abstraction, inheritance, and polymorphism.",
    prompt: "Explain the four pillars of object-oriented programming with practical examples.",
    tests: ["Define encapsulation, abstraction, inheritance, and polymorphism.", "Use examples instead of memorized lines."],
    commonMistake: "Giving definitions without showing where each concept appears in code.",
    approachHint: "Use one small domain example and map each OOP pillar to that example.",
  }),
  q({
    frontendId: "10",
    slug: "database-isolation-levels",
    title: "Database Isolation Levels",
    category: "cs-fundamentals",
    difficulty: "Hard",
    tags: ["DBMS", "Transactions", "Concurrency"],
    acceptanceRate: 57,
    summary: "A deeper DBMS question about dirty reads, non-repeatable reads, and phantom reads.",
    prompt: "Explain database isolation levels and the anomalies they prevent.",
    tests: ["Mention read uncommitted, read committed, repeatable read, and serializable.", "Explain dirty, non-repeatable, and phantom reads."],
    commonMistake: "Listing isolation levels without describing what changes between them.",
    approachHint: "Use concurrent transactions and show which anomaly each level allows or prevents.",
  }),

  q({
    frontendId: "1",
    slug: "design-url-shortener",
    title: "Design a URL Shortener",
    category: "system-design",
    difficulty: "Medium",
    tags: ["Scalability", "Database Design", "Caching"],
    acceptanceRate: 71,
    summary: "Practice requirements, APIs, storage, short-code generation, redirects, and scale trade-offs.",
    prompt: "Design a URL shortener like bit.ly. Cover functional requirements, non-functional requirements, APIs, data model, short-code generation, redirects, and reliability.",
    tests: ["Discuss create and redirect APIs.", "Explain unique short-code generation, lookup caching, and collision handling."],
    commonMistake: "Jumping into components before clarifying scale, read-write ratio, expiry, and collisions.",
    approachHint: "Start with requirements, estimate traffic, design APIs, then discuss storage, cache, collision strategy, and failure cases.",
  }),
  q({
    frontendId: "2",
    slug: "design-notification-system",
    title: "Design a Notification System",
    category: "system-design",
    difficulty: "Hard",
    tags: ["Queues", "Reliability", "Fanout"],
    acceptanceRate: 62,
    summary: "Practice channels, queueing, preferences, retries, provider failures, and delivery guarantees.",
    prompt: "Design a notification system that can send email, SMS, and push notifications at scale while respecting user preferences and retry policies.",
    tests: ["Cover preferences, templates, queues, workers, and provider failures.", "Discuss idempotency, rate limits, retries, and observability."],
    commonMistake: "Treating notifications as a direct API call instead of an asynchronous workflow.",
    approachHint: "Separate request ingestion, preference checks, queueing, channel workers, provider integrations, and status tracking.",
  }),
  q({
    frontendId: "3",
    slug: "design-chat-application",
    title: "Design a Chat Application",
    category: "system-design",
    difficulty: "Hard",
    tags: ["WebSockets", "Messaging", "Storage"],
    acceptanceRate: 60,
    summary: "A real-time system design question about online presence, delivery, and message storage.",
    prompt: "Design a chat app that supports one-on-one messaging, group chats, delivery status, and message history.",
    tests: ["Mention WebSockets or long polling.", "Discuss ordering, persistence, offline delivery, and fanout."],
    commonMistake: "Ignoring message ordering and offline users.",
    approachHint: "Design connection service, message service, storage, queues, and presence separately.",
  }),
  q({
    frontendId: "4",
    slug: "design-rate-limiter",
    title: "Design a Rate Limiter",
    category: "system-design",
    difficulty: "Medium",
    tags: ["Algorithms", "Redis", "API Gateway"],
    acceptanceRate: 68,
    summary: "A focused system design question about limiting requests at scale.",
    prompt: "Design a rate limiter for an API gateway that supports user-specific and IP-specific limits.",
    tests: ["Discuss fixed window, sliding window, or token bucket.", "Mention distributed counters and Redis-style storage."],
    commonMistake: "Only describing an in-memory counter that breaks across multiple servers.",
    approachHint: "Compare algorithms, then choose a distributed storage approach with expiry and atomic updates.",
  }),
  q({
    frontendId: "5",
    slug: "design-news-feed",
    title: "Design a News Feed",
    category: "system-design",
    difficulty: "Hard",
    tags: ["Fanout", "Ranking", "Caching"],
    acceptanceRate: 58,
    summary: "A social feed design question about fanout, ranking, freshness, and celebrity users.",
    prompt: "Design a news feed that shows posts from followed users with ranking and near real-time updates.",
    tests: ["Discuss fanout-on-write vs fanout-on-read.", "Mention ranking, cache invalidation, and high-follower accounts."],
    commonMistake: "Assuming the same feed generation strategy works for all users.",
    approachHint: "Use hybrid fanout, separate ranking service, and caching for feed pages.",
  }),
  q({
    frontendId: "6",
    slug: "design-file-storage-service",
    title: "Design a File Storage Service",
    category: "system-design",
    difficulty: "Medium",
    tags: ["Object Storage", "Metadata", "Consistency"],
    acceptanceRate: 64,
    summary: "A storage design problem about uploads, metadata, sharing, and reliability.",
    prompt: "Design a cloud file storage service like Google Drive for upload, download, sharing, and metadata search.",
    tests: ["Cover object storage and metadata DB.", "Discuss chunked uploads, permissions, and versioning."],
    commonMistake: "Putting large files directly into the relational database.",
    approachHint: "Separate binary storage from metadata, then design upload flow, permissions, and consistency.",
  }),
  q({
    frontendId: "7",
    slug: "design-video-streaming-platform",
    title: "Design a Video Streaming Platform",
    category: "system-design",
    difficulty: "Hard",
    tags: ["CDN", "Encoding", "Scalability"],
    acceptanceRate: 55,
    summary: "A media system question about upload, transcoding, storage, CDN, and playback latency.",
    prompt: "Design a video streaming platform that supports upload, transcoding, adaptive playback, and global delivery.",
    tests: ["Mention transcoding pipelines and CDN.", "Discuss metadata, thumbnails, and adaptive bitrate streaming."],
    commonMistake: "Focusing only on storage and ignoring encoding and delivery.",
    approachHint: "Break the system into ingestion, processing, storage, CDN delivery, and playback analytics.",
  }),
  q({
    frontendId: "8",
    slug: "design-search-autocomplete",
    title: "Design Search Autocomplete",
    category: "system-design",
    difficulty: "Medium",
    tags: ["Trie", "Ranking", "Caching"],
    acceptanceRate: 66,
    summary: "A search design question about prefix lookup, ranking, freshness, and latency.",
    prompt: "Design an autocomplete service that returns top suggestions as a user types a query prefix.",
    tests: ["Discuss trie or prefix index.", "Mention ranking, updates, cache, and latency budgets."],
    commonMistake: "Returning all matches without discussing top-k ranking.",
    approachHint: "Use prefix indexes with precomputed top suggestions and periodic refresh for popular queries.",
  }),
  q({
    frontendId: "9",
    slug: "design-payment-system",
    title: "Design a Payment System",
    category: "system-design",
    difficulty: "Hard",
    tags: ["Payments", "Idempotency", "Reliability"],
    acceptanceRate: 52,
    summary: "A reliability-heavy design question about correctness, idempotency, retries, and reconciliation.",
    prompt: "Design a payment processing system that handles checkout, payment provider calls, retries, and reconciliation.",
    tests: ["Discuss idempotency keys and state machine.", "Mention provider callbacks, retries, and reconciliation jobs."],
    commonMistake: "Retrying payments without idempotency, which can double-charge users.",
    approachHint: "Model payment states carefully and make all provider interactions idempotent.",
  }),
  q({
    frontendId: "10",
    slug: "design-ride-hailing-service",
    title: "Design a Ride Hailing Service",
    category: "system-design",
    difficulty: "Hard",
    tags: ["Geo Indexing", "Matching", "Real Time"],
    acceptanceRate: 54,
    summary: "A large-scale design prompt about rider-driver matching, geospatial queries, and trip state.",
    prompt: "Design a ride hailing service that matches riders with nearby drivers and tracks trip status in real time.",
    tests: ["Discuss geospatial indexing and matching.", "Mention trip state machine, location updates, pricing, and availability."],
    commonMistake: "Ignoring high-frequency driver location updates and stale availability.",
    approachHint: "Separate location ingestion, matching, trip state, pricing, and notification flows.",
  }),

  q({
    frontendId: "1",
    slug: "monthly-transactions-i",
    title: "Monthly Transactions I",
    category: "sql",
    difficulty: "Medium",
    tags: ["Aggregation", "GROUP BY", "CASE"],
    acceptanceRate: 73,
    summary: "A SQL reporting question that tests grouping, conditional aggregation, and date formatting.",
    prompt: "Write a query to find transaction count, approved transaction count, total amount, and approved amount for each month and country.",
    tests: ["Use GROUP BY on month and country.", "Use conditional aggregation for approved rows."],
    commonMistake: "Filtering approved rows in WHERE, which removes rows needed for total counts.",
    approachHint: "Group all rows first, then use CASE expressions inside aggregate functions.",
  }),
  q({
    frontendId: "2",
    slug: "customers-who-bought-all-products",
    title: "Customers Who Bought All Products",
    category: "sql",
    difficulty: "Medium",
    tags: ["COUNT DISTINCT", "HAVING", "Subquery"],
    acceptanceRate: 70,
    summary: "A set comparison query that checks distinct counting and careful grouping.",
    prompt: "Write a query to report customer IDs of customers who bought every product listed in the Product table.",
    tests: ["Group purchases by customer.", "Compare COUNT(DISTINCT product_key) with total product count."],
    commonMistake: "Counting raw rows instead of distinct product keys.",
    approachHint: "Use HAVING with COUNT(DISTINCT product_key) equal to the product table count.",
  }),
  q({
    frontendId: "3",
    slug: "second-highest-salary",
    title: "Second Highest Salary",
    category: "sql",
    difficulty: "Medium",
    tags: ["Subquery", "DISTINCT", "LIMIT"],
    acceptanceRate: 76,
    summary: "A salary query that tests duplicates, NULL behavior, and ordering.",
    prompt: "Write a query to return the second highest distinct salary from an Employee table. Return NULL if it does not exist.",
    tests: ["Handle duplicate salaries.", "Return NULL when there is no second highest salary."],
    commonMistake: "Using OFFSET without removing duplicates.",
    approachHint: "Use DISTINCT salaries and either LIMIT/OFFSET or a MAX below the highest salary.",
  }),
  q({
    frontendId: "4",
    slug: "department-highest-salary",
    title: "Department Highest Salary",
    category: "sql",
    difficulty: "Medium",
    tags: ["JOIN", "GROUP BY", "Window Function"],
    acceptanceRate: 68,
    summary: "A join and ranking problem about finding the top salary per department.",
    prompt: "Write a query to find employees who have the highest salary in each department.",
    tests: ["Join Employee and Department.", "Handle ties correctly."],
    commonMistake: "Returning only one employee per department even when multiple employees tie.",
    approachHint: "Use a subquery with MAX salary per department or a ranking window function.",
  }),
  q({
    frontendId: "5",
    slug: "rank-scores",
    title: "Rank Scores",
    category: "sql",
    difficulty: "Medium",
    tags: ["Window Function", "DENSE_RANK", "ORDER BY"],
    acceptanceRate: 67,
    summary: "A window function question about dense ranking without gaps.",
    prompt: "Write a query to rank scores from highest to lowest using dense ranking.",
    tests: ["Use DENSE_RANK or equivalent.", "Scores with ties should have the same rank and no gaps."],
    commonMistake: "Using RANK when the expected output needs no gaps.",
    approachHint: "Apply DENSE_RANK over descending score order.",
  }),
  q({
    frontendId: "6",
    slug: "employees-earning-more-than-managers",
    title: "Employees Earning More Than Their Managers",
    category: "sql",
    difficulty: "Easy",
    tags: ["Self Join", "Comparison"],
    acceptanceRate: 82,
    summary: "A self-join interview question about comparing rows in the same table.",
    prompt: "Write a query to find employees whose salary is greater than their manager's salary.",
    tests: ["Self join Employee as worker and manager.", "Compare worker salary against manager salary."],
    commonMistake: "Joining on employee id instead of manager id.",
    approachHint: "Join employee.managerId to manager.id, then filter by salary comparison.",
  }),
  q({
    frontendId: "7",
    slug: "delete-duplicate-emails",
    title: "Delete Duplicate Emails",
    category: "sql",
    difficulty: "Easy",
    tags: ["DELETE", "Self Join", "Duplicates"],
    acceptanceRate: 79,
    summary: "A duplicate cleanup question that tests self-join delete logic.",
    prompt: "Write a SQL statement to delete duplicate emails while keeping the row with the smallest id.",
    tests: ["Keep the smallest id for each email.", "Delete only duplicate rows."],
    commonMistake: "Deleting all rows for an email instead of preserving one row.",
    approachHint: "Self join rows with the same email and delete the row with the larger id.",
  }),
  q({
    frontendId: "8",
    slug: "consecutive-numbers",
    title: "Consecutive Numbers",
    category: "sql",
    difficulty: "Medium",
    tags: ["Self Join", "Window Function", "Sequences"],
    acceptanceRate: 63,
    summary: "A sequence detection query for finding values appearing in consecutive rows.",
    prompt: "Find all numbers that appear at least three times consecutively in a Logs table.",
    tests: ["Detect three consecutive ids with the same value.", "Return each qualifying number once."],
    commonMistake: "Counting total occurrences instead of consecutive occurrences.",
    approachHint: "Use self joins on adjacent ids or window functions with LAG.",
  }),
  q({
    frontendId: "9",
    slug: "game-play-analysis-iv",
    title: "Game Play Analysis IV",
    category: "sql",
    difficulty: "Medium",
    tags: ["Aggregation", "Date", "Retention"],
    acceptanceRate: 59,
    summary: "A retention-style SQL problem about first activity and next-day login.",
    prompt: "Report the fraction of players who logged in again on the day after their first login date.",
    tests: ["Find each player's first login.", "Check whether they returned exactly one day later."],
    commonMistake: "Checking any later login instead of the next calendar day.",
    approachHint: "Find first login per player, join back on first date plus one day, then divide by total players.",
  }),
  q({
    frontendId: "10",
    slug: "exchange-seats",
    title: "Exchange Seats",
    category: "sql",
    difficulty: "Medium",
    tags: ["CASE", "Ordering", "Math"],
    acceptanceRate: 65,
    summary: "A SQL transformation question about swapping adjacent seat ids.",
    prompt: "Write a query to swap every two consecutive students' seats. If the number of students is odd, the last seat remains unchanged.",
    tests: ["Swap id 1 with 2, 3 with 4, and so on.", "Keep the last odd id unchanged."],
    commonMistake: "Changing the names instead of producing the swapped seat ordering.",
    approachHint: "Use CASE to compute the new id order and sort by that computed id.",
  }),
];

export const publicQuestions: PublicQuestionPreview[] =
  Array.isArray(generatedCatalog) && generatedCatalog.length > 0
    ? (generatedCatalog as PublicQuestionPreview[])
    : fallbackQuestions;

export function getQuestionsByCategory(category: PublicQuestionCategory) {
  return publicQuestions.filter((question) => question.category === category);
}

export function getQuestionBySlug(category: PublicQuestionCategory, slug: string) {
  return publicQuestions.find((question) => question.category === category && question.slug === slug);
}

export function getLoginPath(nextPath: string) {
  return `/login?next=${encodeURIComponent(nextPath)}`;
}
